domain: elliothatch.github.io
author: elliot hatch
email: elliot.hatch@gmail.com
twitter: neurotischism
title: neurotischism

permalink: /:catagories/:title
exclude:
- README.md

include:
- _stylesheets
safe: true
lsi: false